[app]

title = "NodeScriptKit - 脚本工具集合"
splash = """

███╗   ██╗ ██████╗ ██████╗ ███████╗███████╗ ██████╗██████╗ ██╗██████╗ ████████╗██╗  ██╗██╗████████╗
████╗  ██║██╔═══██╗██╔══██╗██╔════╝██╔════╝██╔════╝██╔══██╗██║██╔══██╗╚══██╔══╝██║ ██╔╝██║╚══██╔══╝
██╔██╗ ██║██║   ██║██║  ██║█████╗  ███████╗██║     ██████╔╝██║██████╔╝   ██║   █████╔╝ ██║   ██║   
██║╚██╗██║██║   ██║██║  ██║██╔══╝  ╚════██║██║     ██╔══██╗██║██╔═══╝    ██║   ██╔═██╗ ██║   ██║   
██║ ╚████║╚██████╔╝██████╔╝███████╗███████║╚██████╗██║  ██║██║██║        ██║   ██║  ██╗██║   ██║   
╚═╝  ╚═══╝ ╚═════╝ ╚═════╝ ╚══════╝╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝╚═╝        ╚═╝   ╚═╝  ╚═╝╚═╝   ╚═╝   
                                                                                                         
"""
splash_timeout = 500 # ms
entry = 'main'

[local]
include = [
    '/etc/nsk/modules.d/default/*.toml',
    '/etc/nsk/modules.d/extend/*.toml',
]

[remote]
subscribes = [
    # remote urls
]
